name: AI Code Reviewer

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  review:
    if: contains(github.event.comment.body, 'AI Review')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: martinodonnell/scout-skills@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4"
          exclude: "**/*.json, **/*.md"
